image: docker:latest
services:
- docker:18.06.0-dind

variables:
  VERSION: 1.0.0
  DOCKER_DRIVER: overlay
  CONTAINER_URL: registry.gitlab.com
  CONTAINER_PATH: /vibent/vibent-entrypoint
  CONTAINER_IMAGE: ${CONTAINER_URL}${CONTAINER_PATH}

stages:
- dockerize
- deploy

dockerize:
  stage: dockerize
  only:
  - develop
  when: manual
  allow_failure: false
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CONTAINER_URL
  - docker pull $CONTAINER_IMAGE:latest || true
  - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$VERSION --tag $CONTAINER_IMAGE:latest .
  - docker push $CONTAINER_IMAGE:$VERSION
  - docker push $CONTAINER_IMAGE:latest

deploy:
  stage: deploy
  only:
  - develop
  script:
  - apk add --update curl && rm -rf /var/cache/apk/*
  - curl -X POST -d "{\"token\":\"$AWS_UTIL_TOKEN\",\"restart\":\"vibent-entrypoint\"}" https://admin.dev.vibent.com